# Generated by Django 4.2.6 on 2023-10-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_price', '0005_delete_datasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='datasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('open', models.CharField(max_length=255, verbose_name='Open')),
                ('high', models.CharField(max_length=255, verbose_name='High')),
                ('low', models.CharField(max_length=255, verbose_name='Low')),
                ('close', models.CharField(max_length=255, verbose_name='Close')),
                ('volume', models.CharField(max_length=255, verbose_name='Volume')),
            ],
        ),
    ]
