# Generated by Django 4.2.6 on 2023-10-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0008_load_lstm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='load_lstm',
        ),
    ]
