# Generated by Django 4.2.6 on 2023-10-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0014_delete_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.PositiveIntegerField()),
            ],
        ),
    ]
