# Generated by Django 4.2.6 on 2023-10-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0015_stockprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='load_lstm',
        ),
    ]
