# Generated by Django 4.2.6 on 2023-10-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0018_rename_timestamp_stockprice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprice',
            old_name='close_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='high_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='low_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='open_price',
            new_name='open',
        ),
    ]
