# Generated by Django 4.2.6 on 2023-11-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0021_load_lstm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
