# Generated by Django 4.2.6 on 2023-11-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0023_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastLoadedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('last_loaded_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
