# Generated by Django 4.2.6 on 2023-11-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0025_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastloadeddate',
            name='last_loaded_date',
            field=models.DateTimeField(default='2021-01-01 00:00:00'),
        ),
    ]
