# Generated by Django 4.2.6 on 2023-11-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0028_alter_lastloadeddate_last_loaded_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastLoadedDate',
        ),
    ]
