# Generated by Django 4.2.6 on 2023-11-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0039_delete_lastloadeddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
