# Generated by Django 4.2.6 on 2023-11-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0041_lastloadeddate_stockprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastLoadedDate',
        ),
    ]
