# Generated by Django 4.2.6 on 2023-11-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0043_lastloadeddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastLoadedDate',
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
