# Generated by Django 4.2.3 on 2024-02-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0045_lastloadeddate_stockprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='load_lstm',
        ),
    ]
