# Generated by Django 4.2.3 on 2024-02-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0047_load_lstm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='load_lstm',
        ),
    ]
