# Generated by Django 4.2.3 on 2024-02-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0048_delete_load_lstm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load_LSTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('model_file', models.FileField(upload_to='pretrained_models/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
