# Generated by Django 4.2.3 on 2024-03-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_price', '0050_login_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login1',
        ),
    ]
